"use strict";

module.exports = {
  block: require("./block"),
  bold: require("./text"),
  comment: require("./text"),
  headline: require("./headline"),
  horizontalRule: require("./text"),
  italic: require("./text"),
  keyword: require("./text"),
  link: require("./link"),
  list: require("./list"),
  ["list.item"]: require("./text"),
  paragraph: require("./all"),
  document: require("./all"),
  section: require("./all"),
  strikeThrough: require("./text"),
  table: require("./table"),
  text: require("./text"),
  ["text.plain"]: require("./text"),
  stars: require("./all"),
  tags: require("./tags"),
  newline: require("./all"),
  ["list.item.bullet"]: require("./text"),
  underline: require("./text"),
  verbatim: require("./text"),
  code: require("./text"),
  planning: require("./text"),
  whitespace: require("./text"),
  ["footnote.definition"]: require("./text"),
  drawer: require("./drawer"),
  timestamp: require("./timestamp"),
};
